/**
 * Subscription Plan Seeds — Platform billing tiers.
 *
 * 4 tiers: Starter → Growth → Professional → Enterprise
 * Prices in INR (₹/month or ₹/year)
 */

const subscriptionPlanSeeds = [
  {
    name: 'Starter',
    slug: 'starter',
    description: 'Perfect for small clinics and solo practitioners.',
    price: { monthly: 999, annually: 9999 },
    currency: 'INR',
    trialDays: 14,
    isPopular: false,
    sortOrder: 1,
    limits: {
      maxUsers:       5,
      maxPatients:    500,
      maxDoctors:     2,
      storageGB:      5,
      maxLocations:   1,
      apiCallsPerDay: 0,
    },
    features: {
      patientsModule:     true,
      doctorsModule:      true,
      appointmentsModule: true,
      billingModule:      true,
      pharmacyModule:     false,
      laboratoryModule:   false,
      wardsModule:        false,
      advancedReports:    false,
      apiAccess:          false,
      whiteLabel:         false,
      auditLogs:          false,
      customRoles:        false,
      multiLocation:      false,
      smsNotifications:   false,
      whatsappNotifications: false,
    },
  },
  {
    name: 'Growth',
    slug: 'growth',
    description: 'For growing multi-specialty clinics and small hospitals.',
    price: { monthly: 2999, annually: 29999 },
    currency: 'INR',
    trialDays: 14,
    isPopular: true,
    sortOrder: 2,
    limits: {
      maxUsers:       25,
      maxPatients:    5000,
      maxDoctors:     10,
      storageGB:      25,
      maxLocations:   2,
      apiCallsPerDay: 0,
    },
    features: {
      patientsModule:     true,
      doctorsModule:      true,
      appointmentsModule: true,
      billingModule:      true,
      pharmacyModule:     true,
      laboratoryModule:   true,
      wardsModule:        false,
      advancedReports:    false,
      apiAccess:          false,
      whiteLabel:         false,
      auditLogs:          true,
      customRoles:        false,
      multiLocation:      false,
      smsNotifications:   true,
      whatsappNotifications: false,
    },
  },
  {
    name: 'Professional',
    slug: 'professional',
    description: 'Full-featured for established hospitals with advanced needs.',
    price: { monthly: 7999, annually: 79999 },
    currency: 'INR',
    trialDays: 14,
    isPopular: false,
    sortOrder: 3,
    limits: {
      maxUsers:       100,
      maxPatients:    50000,
      maxDoctors:     50,
      storageGB:      100,
      maxLocations:   5,
      apiCallsPerDay: 10000,
    },
    features: {
      patientsModule:     true,
      doctorsModule:      true,
      appointmentsModule: true,
      billingModule:      true,
      pharmacyModule:     true,
      laboratoryModule:   true,
      wardsModule:        true,
      advancedReports:    true,
      apiAccess:          true,
      whiteLabel:         false,
      auditLogs:          true,
      customRoles:        true,
      multiLocation:      true,
      smsNotifications:   true,
      whatsappNotifications: true,
    },
  },
  {
    name: 'Enterprise',
    slug: 'enterprise',
    description: 'Unlimited scale. Custom SLA. White-label. Dedicated support.',
    price: { monthly: 19999, annually: 199999 },
    currency: 'INR',
    trialDays: 30,
    isPopular: false,
    sortOrder: 4,
    limits: {
      maxUsers:       -1,       // -1 = unlimited
      maxPatients:    -1,
      maxDoctors:     -1,
      storageGB:      1000,
      maxLocations:   -1,
      apiCallsPerDay: -1,
    },
    features: {
      patientsModule:     true,
      doctorsModule:      true,
      appointmentsModule: true,
      billingModule:      true,
      pharmacyModule:     true,
      laboratoryModule:   true,
      wardsModule:        true,
      advancedReports:    true,
      apiAccess:          true,
      whiteLabel:         true,
      auditLogs:          true,
      customRoles:        true,
      multiLocation:      true,
      smsNotifications:   true,
      whatsappNotifications: true,
    },
  },
];

module.exports = subscriptionPlanSeeds;
